// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import GroupinviteController from "./groupinvite_controller"
application.register("groupinvite", GroupinviteController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InvitationController from "./invitation_controller"
application.register("invitation", InvitationController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import SignupController from "./signup_controller"
application.register("signup", SignupController)
