// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BankController from "./bank_controller"
application.register("bank", BankController)

import GroupinviteController from "./groupinvite_controller"
application.register("groupinvite", GroupinviteController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InvitationController from "./invitation_controller"
application.register("invitation", InvitationController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import PassgenerateController from "./passgenerate_controller"
application.register("passgenerate", PassgenerateController)

import PassnewController from "./passnew_controller"
application.register("passnew", PassnewController)

import SearchcardsController from "./searchcards_controller"
application.register("searchcards", SearchcardsController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import SignupController from "./signup_controller"
application.register("signup", SignupController)
